# Generated by Django 5.0.3 on 2024-03-17 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_in_time_employee_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='in_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='out_time',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='emp_app.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
